### PR TITLE
fix(ddl): wait running add index before CREATE TABLE LIKE

### LINKED ISSUE #3832: fix `create table like` in schemastore
### What did you do?

For the DDL statement create table a like b, we need to add both tables a and b to the DDLEvent.BlockedTables. Otherwise, if there is another DDL operation like add index to b that occurs before the create table, the create table like will not wait for the index addition to finish. Consequently, table a will be created without the expected index.

### What did you expect to see?

_No response_

### What did you see instead?

None

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #3832

### What is changed and how it works?

Fix downstream schema inconsistency for CREATE TABLE ... LIKE ... when the referenced table has a long-running ADD INDEX that is still running/queueing in downstream TiDB. In this case, CREATE TABLE b LIKE a may copy the current downstream schema of a before the index becomes visible, causing b to miss the index.

This PR makes CREATE TABLE ... LIKE ... wait for any running async ADD INDEX on the referenced table before executing the CREATE TABLE ... LIKE ....

  - Detect CREATE TABLE ... LIKE ... in schemastore when building DDLEvent, extract the referenced table, and populate BlockedTableNames with that referenced table.
  - Adjust mysql/TiDB sink behavior so CREATE TABLE is eligible for async-DDL waiting logic; for normal create table (no LIKE), this is a no-op because BlockedTableNames is empty. For CREATE TABLE ... LIKE ..., it triggers waiting on the referenced table’s running ADD INDEX job.

#### Tests 

- Unit test
- Integration test
- Manual test

##### Will it cause performance regression or break compatibility?
None
##### Do you need to update user documentation, design documentation or monitoring documentation?
None
### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

File: pkg/sink/mysql/helper.go [hunk 1]
```diff
@@ -399,8 +399,6 @@ func needSwitchDB(event *commonEvent.DDLEvent) bool {
 
 func needWaitAsyncExecDone(t timodel.ActionType) bool {
 	switch t {
-	case timodel.ActionCreateTable, timodel.ActionCreateTables:
```
Comment (wk989898) [inline pkg/sink/mysql/helper.go]: I think it is not a good idea to remove this. If there are lots of create table DDL, every table will query the downstream. It may affect performance. Could we handle the `create table like` separately?

Comment (wlwilliamx) [reply pkg/sink/mysql/helper.go]: Removing `create table` and `create tables` here is irrelevant, because only `create table like` will have blocked table names. Only when there are blocked table names will the query `add index` and wait.

Comment (hongyunyan) [reply pkg/sink/mysql/helper.go]: Why we could remove this function?
