### PR TITLE
schemastore: fix exchange partition name unquoting

### LINKED ISSUE #4450: exchange partition query rebuild corrupts partition names containing backticks
### What did you do?

`buildPersistedDDLEventForExchangePartition` uses `strings.Replace(partName, "`", "", -1)` to unquote the partition name.

  This removes all backticks instead of only stripping the outer identifier quotes, so partition names containing escaped backticks are corrupted.

### What did you expect to see?

_No response_

### What did you see instead?

None

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #4450 

### What is changed and how it works?

This pull request resolves a bug in the handling of `EXCHANGE PARTITION` DDL statements where partition names, especially those containing escaped backticks, were not being unquoted correctly. By implementing a robust `UnquoteName` utility and applying it to the relevant DDL parsing paths, the change ensures accurate processing of schema changes, preventing potential data inconsistencies or errors in schema replication.

### Highlights

* **New Utility Function**: Introduced a new `UnquoteName` utility function in the `pkg/common` package to correctly handle MySQL identifier unquoting, including the unescaping of doubled backticks.
* **DDL Parsing Fix**: Integrated the `UnquoteName` function into the DDL handling logic for `EXCHANGE PARTITION` statements within the `schemastore` and `event` packages, ensuring proper parsing of partition names that may contain escaped backticks.
* **Improved Test Coverage**: Updated existing unit tests and added new dedicated unit tests for the `UnquoteName` function to validate its correctness across various scenarios, including unquoted, quoted, and quoted names with escaped backticks.

#### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Review by tenfyzhong — APPROVED** [review]

File: logservice/schemastore/persist_storage_test.go [hunk 1]
```diff
@@ -3454,7 +3454,7 @@ func TestBuildPersistedDDLEventEscapesIdentifiers(t *testing.T) {
 		})
 
 		assert.Equal(t,
-			"ALTER TABLE `part``db`.`pt``x` EXCHANGE PARTITION `p0` WITH TABLE `normal``db`.`normal``t` WITHOUT VALIDATION",
+			"ALTER TABLE `part``db`.`pt``x` EXCHANGE PARTITION `p``0` WITH TABLE `normal``db`.`normal``t` WITHOUT VALIDATION",
```
Comment (wk989898) [inline logservice/schemastore/persist_storage_test.go]: ditto

**Review by wk989898 — APPROVED** [review]
