### PR TITLE
sink: fix a bug that may cause data loss while closing Writer failed 

### LINKED ISSUE #3080: unstable storage integration test
### What did you do?

run integration test **ddl_for_split_tables_with_random_merge_and_split** and **ddl_for_split_tables**

### What did you expect to see?

_No response_

### What did you see instead?

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Fticdc%2Fpull_cdc_storage_integration_heavy/detail/pull_cdc_storage_integration_heavy/3653/pipeline

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Fticdc%2Fpull_cdc_storage_integration_light/detail/pull_cdc_storage_integration_light/4132/pipeline
### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### LINKED ISSUE #3371: unstable ddl_for_split_tables storage test
### What did you do?

run integration test ddl_for_split_tables

### What did you expect to see?

_No response_

### What did you see instead?

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Fticdc%2Fpull_cdc_storage_integration_light/detail/pull_cdc_storage_integration_light/4510/pipeline

Some of dml events send to the dispatcher but don't send to the downstream
### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #3371 close #3080

### What is changed and how it works?
In the previous implementation, the error of `writer.Close` was not handled, and some DMLs may upload failed.
This error should block the advance and cause the changefeed to finally restart.
More details in https://github.com/pingcap/tiflow/issues/12436

#### Tests 

- Unit test
- Integration test

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

File: downstreamadapter/sink/cloudstorage/writer.go [hunk 1]
```diff
@@ -255,22 +255,17 @@ func (d *writer) writeDataFile(ctx context.Context, path string, task *singleTab
...
 		if _, inErr = writer.Write(ctx, buf.Bytes()); inErr != nil {
 			return 0, 0, inErr
 		}
+		if inErr = writer.Close(ctx); inErr != nil {
+			log.Error("failed to close writer", zap.Error(inErr),
+				zap.Int("workerID", d.id),
+				zap.Any("table", task.tableInfo.TableName),
+				zap.String("keyspace", d.changeFeedID.Keyspace()),
+				zap.Stringer("changefeed", d.changeFeedID.ID()))
+			return 0, 0, inErr
```
Comment (asddongmen) [inline downstreamadapter/sink/cloudstorage/writer.go]: You must make sure this error is thrown to the maintainer and triggers changefeed restat -- this prevents the disptahcer from getting stuck due to **missing callbacks**.

Comment (wk989898) [reply downstreamadapter/sink/cloudstorage/writer.go]: I have checked this and determined the maintainer will receive this error

**Review by hongyunyan — APPROVED** [review]
Rest is LGTM

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]
