### PR TITLE
server: avoid server hang when sub module exited

### LINKED ISSUE #2314: CDC server hang when etcd session done
After the etcd session expires (etcd session done), most TiCDC components (e.g., core synchronization modules) exit with error as expected. Additionally, both the TCP server and HTTP server (critical for CDC's network communication) also exit normally.

However, the TiCDC main server process fails to exit with an error as intended and instead enters an unresponsive (zombie-like) state—it remains running but no longer processes tasks, responds to requests, or logs valid information.

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #2314

### What is changed and how it works?
1. Let sub modules exit successfully
2. Let tcp server exit later
3. Set a timeout if some sub modules take too long to exit
#### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
```
[WARN] [etcd_watcher.go:70] ["session is disconnected"] [error="[CDC:ErrEtcdSessionDone]the etcd session is done"] [errorVerbose="[CDC:ErrEtcdSessionDone]the etcd session is done\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20250523034308-74f78ae071ee/normalize.go:177\ngithub.com/pingcap/ticdc/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/ticdc/pkg/orchestrator/etcd_worker.go:192\ngithub.com/pingcap/ticdc/server/watcher.(*EtcdWatcher).RunEtcdWorker\n\tgithub.com/pingcap/ticdc/server/watcher/etcd_watcher.go:61\ngithub.com/pingcap/ticdc/server/watcher.(*NodeManager).Run\n\tgithub.com/pingcap/ticdc/server/watcher/module_node_manager.go:169\ngithub.com/pingcap/ticdc/server.(*server).Run.(*server).Run.func2.func6\n\tgithub.com/pingcap/ticdc/server/server.go:276\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.16.0/errgroup/errgroup.go:93\nruntime.goexit\n\truntime/asm_amd64.s:1700"]
[INFO] [server.go:276] ["sub common module exited"] [module=node-manager]
[INFO] [server.go:293] ["sub module exited"] [module=MaintainerManager]
[INFO] [event_service.go:103] ["event service exited"]
[INFO] [server.go:293] ["sub module exited"] [module=EventService]
[INFO] [event_store.go:322] ["event store exited"]
[INFO] [server.go:293] ["sub module exited"] [module=EventStore]
[INFO] [subscription_client.go:776] ["subscription client handle errors and exit"]
[INFO] [module_election.go:267] ["log coordinator exited normally"] [captureID=8201c3e4-2ce0-4d01-8a98-864ad85a81b1] [error="context canceled"]
[INFO] [region_request_worker.go:214] ["region request worker receive from grpc stream failed"] [workerID=2] [addr=127.0.0.1:20161] [code=Canceled] [error="rpc error: code = Canceled desc = context canceled"]
[INFO] [region_request_worker.go:214] ["region request worker receive from grpc stream failed"] [workerID=3] [addr=127.0.0.1:20161] [code=Canceled] [error="rpc error: code = Canceled desc = context canceled"]
[INFO] [module_election.go:149] ["coordinator stop"] [captureID=8201c3e4-2ce0-4d01-8a98-864ad85a81b1] [coordinatorVersion=318] [error="context canceled"]
[INFO] [region_request_worker.go:171] ["region request worker exits"] [workerID=3] [addr=127.0.0.1:20161] [canceled=true]
[INFO] [region_request_worker.go:171] ["region request worker exits"] [workerID=2] [addr=127.0.0.1:20161] [canceled=true]
[INFO] [subscription_client.go:452] ["subscription client exits"]
[INFO] [server.go:293] ["sub module exited"] [module=SubscriptionClient]
[INFO] [module_election.go:169] ["coordinator resigned successfully"] [captureID=8201c3e4-2ce0-4d01-8a98-864ad85a81b1] [coordinatorVersion=318]
[INFO] [module_election.go:188] ["run coordinator exited normally"] [captureID=8201c3e4-2ce0-4d01-8a98-864ad85a81b1] [coordinatorVersion=318] [error="context canceled"]
[INFO] [server.go:276] ["sub common module exited"] [module=elector]
...
[INFO] [module_grpc.go:63] ["grpc server exited"]
[INFO] [server.go:276] ["sub common module exited"] [module=grpc]
[server.go:130] ["cdc server exits with error"] [error="[CDC:ErrTimeout]timeout%!(EXTRA string=takes too long for all sub modules to exit)"]
```

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

File: tests/integration_tests/capture_session_done_during_task/run.sh [hunk 1]
```diff
@@ -14,6 +14,14 @@ function run() {
 	cd $WORK_DIR
 
 	pd_addr="http://$UP_PD_HOST_1:$UP_PD_PORT_1"
+
+	export GO_FAILPOINTS='github.com/pingcap/ticdc/pkg/orchestrator/EtcdSessionDone=return(true)'
+	run_cdc_server --workdir $WORK_DIR --binary $CDC_BINARY --addr "127.0.0.1:8300" --pd $pd_addr
+	sleep 3
+	check_logs_contains $WORK_DIR "the etcd session is done"
+	export GO_FAILPOINTS=''
+	cleanup_process $CDC_BINARY
```
Comment (asddongmen) [inline tests/integration_tests/capture_session_done_during_task/run.sh:23]: You need to check if the process is exited here rather than cleanup it.

Comment (asddongmen) [reply tests/integration_tests/capture_session_done_during_task/run.sh:23]: Then, we should also make the tcp server exit...

File: server/server.go [hunk 2]
```diff
@@ -52,9 +52,10 @@ import (
 )
 
 const (
-	closeServiceTimeout  = 15 * time.Second
-	cleanMetaDuration    = 10 * time.Second
-	oldArchCheckInterval = 100 * time.Millisecond
+	closeServiceTimeout     = 15 * time.Second
+	cleanMetaDuration       = 10 * time.Second
+	oldArchCheckInterval    = 100 * time.Millisecond
+	gracefulShutdownTimeout = 30 * time.Second
```
Comment (asddongmen) [inline server/server.go:58]: Please add a comment to explain how it works.

File: server/server.go [hunk 3]
```diff
@@ -86,6 +87,11 @@ type server struct {
 	// preServices is the preServices will be start before the server is running
 	// And will be closed when the server is closing
 	preServices []common.Closeable
+
+	// subBaseModules contains base modules that start after PreServices.
+	// These modules will be closed at the end when the server shuts down.
```
Comment (asddongmen) [inline server/server.go:92]:
```suggestion
	// These modules must be closed finally when the CDC server is shutting down.
```

File: server/server.go [hunk 4]
```diff
@@ -253,31 +262,34 @@ func (c *server) Run(ctx context.Context) error {
...
-		err := c.tcpServer.Run(ctx)
-		if err != nil {
-			log.Error("tcp server exited", zap.Error(errors.Trace(err)))
-		}
-		return nil
-	})
-
 	log.Info("server initialized", zap.Any("server", c.info))
-	// start all submodules
+	// base module priority is higher than other sub modules
```
Comment (asddongmen) [inline server/server.go:266]:
```suggestion
	// Base modules have a longer lifecycle compared to other sub-modules; therefore, their context ought to be set as the parent context for the latter.
```
