### PR TITLE
fix(*): move, add, remove, split operator inconsistent after maintainer move

### LINKED ISSUE #3411: add index can not sync to downstream after ticdc rolling restart
### What did you do?

1、create changefeed with tidb downstream
2、run sysbench and add index for one table
3、ticdc rolling restart

### What did you expect to see?

add index can sync to downstream

### What did you see instead?

add index can not sync to downstream after ticdc rolling restart

upstream：

Image

downstream：

Image

### Versions of the cluster

./cdc version
 Release Version: v8.5.4-nextgen.202510.2-6-ge24442c
Git Commit Hash: e24442c0c3873de22ec80d79d964ae85e9c4105b
Git Branch: HEAD
UTC Build Time: 2025-11-28 04:43:31
Go Version: go version go1.24.7 linux/amd64
Failpoint Build: false
Kernel Type: Next Generation
2025-11-28T14:15:54.828+0800

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #3411

During maintainer failover/restart, in-flight dispatcher operators (add/remove/move/split) could be lost. If a dispatcher becomes Stopped/Removed while the corresponding operator state is missing, the span may never be rescheduled, leading to “lost dispatcher” and stalled replication. This is reproducible when dispatcher creation/close is blocked (e.g. move-table/split/remove in progress) and affects both default and redo modes.

  ### What is changed and how it works?

  - Persist in-flight operators across failover via bootstrap
      - Add OperatorType to ScheduleDispatcherRequest and include operators in MaintainerBootstrapResponse (heartbeatpb/heartbeat.proto).
      - DispatcherManager records current working operators (currentOperatorMap / redoCurrentOperatorMap) when handling schedule requests, and clears them when the dispatcher is created/cleaned (downstreamadapter/dispatchermanager/...).
      - DispatcherOrchestrator returns these operators in bootstrap responses (downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go).
  - Restore operator consistency during maintainer bootstrap
      - During FinishBootstrap, restore reported in-flight operators before rebuilding task/schema state (maintainer/maintainer_controller_bootstrap.go).
      - For Create: ensure an absent replica-set exists and re-issue an add operator.
      - For Remove:
          - O_Remove: re-issue remove; if the table is gone, drop the span from the controller.
          - O_Move/O_Split: re-issue the remove stage and mark the span absent on finish so normal scheduling can safely re-add it (target may change after failover).
  - Runtime safety net
      - If a dispatcher reports Stopped/Removed but there is no operator for it, mark the span absent to force rescheduling (maintainer/maintainer_controller.go).
  - Tests / test tooling
      - Add failpoints to keep operators in-progress (NotReadyToCloseDispatcher, BlockCreateDispatcher).
      - Add integration test maintainer_failover_when_operator (covers add/split/move/remove + maintainer failover; default + redo subcases).
      - Add wait param/flag to move-table API/CLI for tests so a move can be initiated without blocking until completion.

#### Tests 

- Unit test
- Integration test
- Manual test

##### Will it cause performance regression or break compatibility?
None
##### Do you need to update user documentation, design documentation or monitoring documentation?
None
### Release note 

```release-note
Fix an issue where table spans could stop replicating after maintainer failover/restart when dispatcher add/remove/move/split operators were in progress.
```

## Summary by CodeRabbit

* **New Features**
  * Added `--wait` flag to move-table operations for controlling blocking behavior during table moves
  * Enhanced operation state preservation across cluster failovers and restarts

* **Bug Fixes**
  * Improved bootstrap to restore in-flight operations on startup
  * Better duplicate operation request handling
  * Enhanced dispatcher lifecycle tracking to prevent orphaned operations

### CODE REVIEW

File: downstreamadapter/dispatcher/redo_dispatcher.go [hunk 1]
```diff
@@ -39,6 +39,7 @@ type RedoDispatcher struct {
 func NewRedoDispatcher(
 	id common.DispatcherID,
 	tableSpan *heartbeatpb.TableSpan,
+	endabledSplit bool,
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply downstreamadapter/dispatcher/redo_dispatcher.go]: done

File: downstreamadapter/dispatcher/basic_dispatcher.go [hunk 2]
```diff
@@ -120,6 +120,7 @@ type BasicDispatcher struct {
 	// or just a part of the table (span). When true, the dispatcher handles the entire table;
 	// when false, it only handles a portion of the table.
 	isCompleteTable bool
+	enabledSplit    bool
```
Comment (hongyunyan) [inline downstreamadapter/dispatcher/basic_dispatcher.go]: why we need this field?

File: downstreamadapter/dispatchermanager/dispatcher_manager.go [hunk 3]
```diff
@@ -87,6 +87,9 @@ type DispatcherManager struct {
 	dispatcherMap *DispatcherMap[*dispatcher.EventDispatcher]
 	// redoDispatcherMap restore all the redo dispatchers in the DispatcherManager, including redo table trigger event dispatcher
 	redoDispatcherMap *DispatcherMap[*dispatcher.RedoDispatcher]
+	// currentOperatorMap stores the current operators for each dispatcher
+	currentOperatorMap     sync.Map // map[span.String()]*dispatcher.CurrentOperator
```
Comment (hongyunyan) [inline downstreamadapter/dispatchermanager/dispatcher_manager.go]: span.String() means dispatcherID?

File: downstreamadapter/dispatchermanager/helper.go [hunk 4]
```diff
@@ -196,6 +209,24 @@ func (h *SchedulerDispatcherRequestHandler) Handle(dispatcherManager *Dispatcher
...
+			log.Warn("scheduleDispatcherRequest config is nil, skip")
+			continue
+		}
+		operatorKey := schedulerDispatcherKey(req.ScheduleDispatcherRequest)
+		if operatorKey == "" {
+			log.Warn("scheduleDispatcherRequest has no valid operator key, skip")
+			continue
+		}
+		// If there is already an operator for the span, skip this request.
+		_, exists := dispatcherManager.currentOperatorMap.Load(operatorKey)
```
Comment (hongyunyan) [inline downstreamadapter/dispatchermanager/helper.go]: Consider this scenario: a dispatcher is performing a merge operation, but before it's finished, a drop table DDL causes the dispatcher to be removed. In this situation, could it happen that the dispatcher holding the operator has now received a new operator?

File: downstreamadapter/dispatchermanager/helper.go [hunk 5]
```diff
@@ -173,6 +173,19 @@ func newSchedulerDispatcherRequestDynamicStream() dynstream.DynamicStream[int, c
 	return ds
 }
 
+func schedulerDispatcherKey(req *heartbeatpb.ScheduleDispatcherRequest) string {
+	if req == nil || req.Config == nil {
+		return ""
+	}
+	if req.Config.Span != nil {
```
Comment (hongyunyan) [inline downstreamadapter/dispatchermanager/helper.go]: why sometimes return span's string, sometimes return dispatcherID?

File: downstreamadapter/dispatchermanager/helper.go (hunk 4 above)
Comment (hongyunyan) [reply downstreamadapter/dispatchermanager/helper.go]: when will these continue happens? It will make the create or remove action skipped.  Is there no correctness issue here?

File: downstreamadapter/dispatchermanager/dispatcher_manager.go (hunk 3 above)
Comment (wlwilliamx) [reply downstreamadapter/dispatchermanager/dispatcher_manager.go]: I believe that currently only the span ID can be used as a unique identifier. The dispatcher ID may change, and the operator essentially wants to schedule the span, so it is necessary to ensure that there is only one span globally.

File: downstreamadapter/dispatchermanager/helper.go (hunk 5 above)
Comment (wlwilliamx) [reply downstreamadapter/dispatchermanager/helper.go]: There's a special case where the maintainer finds that the dispatcher manager reported a working dispatcher, but the span controller doesn't have a corresponding span. The maintainer will then send a remove operator request to remove this dispatcher. Since the span doesn't exist, the request won't include span information; the dispatcher ID will be used instead. However, there won't be a conflict because the span ID and dispatcher ID will never be the same.

File: downstreamadapter/dispatchermanager/helper.go [hunk 6]
```diff
@@ -196,6 +209,24 @@ func (h *SchedulerDispatcherRequestHandler) Handle(dispatcherManager *Dispatcher
 			log.Warn("scheduleDispatcherRequest is nil, skip")
 			continue
 		}
+		if req.Config == nil {
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply downstreamadapter/dispatchermanager/helper.go]: OK

File: maintainer/maintainer_controller_bootstrap.go [hunk 7]
```diff
@@ -409,3 +429,126 @@ func findHoles(currentSpan utils.Map[*heartbeatpb.TableSpan, *replica.SpanReplic
 	}
 	return holes
 }
+
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply maintainer/maintainer_controller_bootstrap.go]: OK

File: downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go [hunk 8]
```diff
@@ -373,6 +373,24 @@ func createBootstrapResponse(
 				Mode:            d.GetMode(),
 			})
 		})
+		manager.GetRedoCurrentOperatorMap().Range(func(key, value any) bool {
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go]: done

File: downstreamadapter/dispatchermanager/helper.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply downstreamadapter/dispatchermanager/helper.go]: done

File: downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go [hunk 9]
```diff
@@ -373,6 +373,24 @@ func createBootstrapResponse(
...
+			req := value.(heartbeatpb.ScheduleDispatcherRequest)
+			_, ok := manager.GetRedoDispatcherMap().Get(common.NewDispatcherIDFromPB(req.Config.DispatcherID))
+			if !ok {
+				log.Error("Redo dispatcher not found, this should not happen",
+					zap.String("changefeed", changefeedID.String()),
+					zap.String("dispatcherID", req.Config.DispatcherID.String()),
+				)
+			}
+
+			response.Operators = append(response.Operators, &heartbeatpb.ScheduleDispatcherRequest{
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go]: If we use a separate struct, the code would require many unnecessary struct conversions. I think simply renaming the existing `ScheduleDispatcherRequest` to indicate that it's a struct used to store operator information would be sufficient.

File: pkg/api/v2/changefeed.go [hunk 10]
```diff
@@ -50,7 +50,7 @@ type ChangefeedInterface interface {
 	// List lists all changefeeds
 	List(ctx context.Context, keyspace string, state string) ([]v2.ChangefeedCommonInfo, error)
 	// Move Table to target node, it just for make test case now. **Not for public use.**
-	MoveTable(ctx context.Context, keyspace string, name string, tableID int64, targetNode string, mode int64) error
+	MoveTable(ctx context.Context, keyspace string, name string, tableID int64, targetNode string, mode int64, wait bool) error
```
Comment (hongyunyan) [inline pkg/api/v2/changefeed.go]: what the 'wait' means? could you please give a description here

File: maintainer/maintainer_controller_bootstrap.go [hunk 11]
```diff
@@ -442,3 +469,220 @@ func findHoles(currentSpan utils.Map[*heartbeatpb.TableSpan, *replica.SpanReplic
...
+		for _, req := range resp.Operators {
+			// Validate
+			if req == nil || req.Config == nil || req.Config.DispatcherID == nil {
+				log.Warn("bootstrap operator config is nil, skip restoring it",
+					zap.String("nodeID", node.String()),
+					zap.String("changefeed", resp.ChangefeedID.String()))
+				continue
+			}
+			dispatcherID := common.NewDispatcherIDFromPB(req.Config.DispatcherID)
+			if dispatcherID.IsZero() {
```
Comment (hongyunyan) [inline maintainer/maintainer_controller_bootstrap.go]: Is dispatcherID.IsZero() necessary?

File: maintainer/maintainer_controller_bootstrap.go [hunk 12]
```diff
@@ -442,3 +469,220 @@ func findHoles(currentSpan utils.Map[*heartbeatpb.TableSpan, *replica.SpanReplic
...
+					zap.String("dispatcherID", dispatcherID.String()),
+					zap.String("operatorType", req.OperatorType.String()),
+					zap.String("scheduleAction", req.ScheduleAction.String()))
+				continue
+			}
+			spanController := c.getSpanController(req.Config.Mode)
+			replicaSet := spanController.GetTaskByID(dispatcherID)
+
+			switch req.ScheduleAction {
+			case heartbeatpb.ScheduleAction_Create:
```
Comment (hongyunyan) [inline maintainer/maintainer_controller_bootstrap.go]: Under what circumstances would the code enter the branches of 534-559 in the `if` statement? Is this possible, or is it just a precautionary logic?

File: maintainer/maintainer_controller_bootstrap.go [hunk 13]
```diff
@@ -442,3 +469,220 @@ func findHoles(currentSpan utils.Map[*heartbeatpb.TableSpan, *replica.SpanReplic
...
+	// Check the original operator of this add operator
+	switch req.OperatorType {
+	// 1. If the original operator is add, just finish it directly by adding a new add operator.
+	// 2. If the original operator is move, which is a remove + add,
+	// just finish the add part so that the move operator is done.
+	// 3. If the original operator is split, which is a remove + add + add...,
+	// same as move, just finish the add part.
+	case heartbeatpb.OperatorType_O_Add, heartbeatpb.OperatorType_O_Move, heartbeatpb.OperatorType_O_Split:
+		op := operator.NewAddDispatcherOperator(spanController, replicaSet, node, heartbeatpb.OperatorType_O_Add)
+		if ok := c.operatorController.AddOperator(op); !ok {
```
Comment (hongyunyan) [inline maintainer/maintainer_controller_bootstrap.go]: operatorController also need to get by mode

File: pkg/applier/_insert_storage.tmp
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply pkg/applier/_insert_storage.tmp]: ok

File: maintainer/maintainer_controller_bootstrap.go (hunk 11 above)
Comment (wlwilliamx) [reply maintainer/maintainer_controller_bootstrap.go]: Not necessary, just in case we forget to pass a dispatcherID

File: maintainer/maintainer_controller_bootstrap.go (hunk 12 above)
Comment (wlwilliamx) [reply maintainer/maintainer_controller_bootstrap.go]: This is possible. If the dispatcher has already been created but the operator hasn't been deleted yet, it will be reported, so spanInfo might not be nil.

File: maintainer/maintainer_controller_bootstrap.go [hunk 14]
```diff
@@ -442,3 +469,220 @@ func findHoles(currentSpan utils.Map[*heartbeatpb.TableSpan, *replica.SpanReplic
...
+				zap.String("nodeID", node.String()),
+				zap.String("changefeed", resp.ChangefeedID.String()),
+				zap.String("dispatcher", op.ID().String()),
+				zap.String("originOperatorType", req.OperatorType.String()),
+				zap.Any("operator", op),
+				zap.Any("replicaSet", replicaSet),
+			)
+			return errors.ErrOperatorIsNil.GenWithStack("add operator failed when bootstrap"), true
+		}
+		op.Start()
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply maintainer/maintainer_controller_bootstrap.go]: Got it, I'll delete this start.

File: downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go [hunk 15]
```diff
@@ -458,3 +440,85 @@ func (m *DispatcherOrchestrator) handleDispatcherError(
...
+}
+
+func retrieveCurrentOperatorsForBootstrapResponse(
+	changefeedID *heartbeatpb.ChangefeedID,
+	manager *dispatchermanager.DispatcherManager,
+	response *heartbeatpb.MaintainerBootstrapResponse,
+) {
+	manager.GetCurrentOperatorMap().Range(func(key, value any) bool {
+		req := value.(dispatchermanager.SchedulerDispatcherRequest)
+		_, ok := manager.GetDispatcherMap().Get(common.NewDispatcherIDFromPB(req.Config.DispatcherID))
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go]: Good suggestion

File: heartbeatpb/heartbeat.proto [hunk 16]
```diff
@@ -108,6 +116,7 @@ message ScheduleDispatcherRequest {
     ChangefeedID changefeedID = 1;
     DispatcherConfig config = 2;
     ScheduleAction scheduleAction = 3;
+    OperatorType operatorType = 4;
```
Comment (wk989898) [inline heartbeatpb/heartbeat.proto]: The operatorType should be an `int` type, and we can define the operatorType in maintainer/operator

File: downstreamadapter/dispatchermanager/dispatcher_manager.go [hunk 17]
```diff
@@ -87,6 +87,9 @@ type DispatcherManager struct {
 	dispatcherMap *DispatcherMap[*dispatcher.EventDispatcher]
 	// redoDispatcherMap restore all the redo dispatchers in the DispatcherManager, including table trigger redo dispatcher
 	redoDispatcherMap *DispatcherMap[*dispatcher.RedoDispatcher]
+	// currentOperatorMap stores the current operators for each dispatcher
+	currentOperatorMap     sync.Map // map[common.DispatcherID]SchedulerDispatcherRequest (in dispatcher manager, not heartbeatpb)
+	redoCurrentOperatorMap sync.Map // map[common.DispatcherID]SchedulerDispatcherRequest (in dispatcher manager, not heartbeatpb)
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply downstreamadapter/dispatchermanager/dispatcher_manager.go]: No, these need to be separated. Just like dispatcherMap and redo DispatcherMap are also separate.

**Review by wk989898 — APPROVED** [review]

File: maintainer/maintainer_controller_bootstrap.go (hunk 12 above)
Comment (hongyunyan) [reply maintainer/maintainer_controller_bootstrap.go]: ps, this function is really long, could you split the function to some small functions?

File: maintainer/operator/operator_remove.go [hunk 18]
```diff
@@ -33,16 +33,36 @@ type removeDispatcherOperator struct {
 	replicaSet     *replica.SpanReplication
 	nodeID         node.ID
 	finished       atomic.Bool
+	postFinish     func()
 	spanController *span.Controller
+	// This remove operator may be a part of move/split operator
```
Comment (hongyunyan) [inline maintainer/operator/operator_remove.go]: Ditto

File: tests/integration_tests/maintainer_failover_when_operator/run.sh [hunk 19]
```diff
@@ -0,0 +1,362 @@
+#!/bin/bash
```
Comment (hongyunyan) [inline tests/integration_tests/maintainer_failover_when_operator/run.sh]: Could you add a description here to describe what is the main purpose for this test, and what is the main steps for the tests. 
Test code is often more complex and harder to read and maintain. Having a comprehensive explanation and step-by-step instructions makes it easier to check and fix test failures later on.

File: maintainer/maintainer_controller_bootstrap.go [hunk 20]
```diff
@@ -442,3 +468,230 @@ func findHoles(currentSpan utils.Map[*heartbeatpb.TableSpan, *replica.SpanReplic
...
+				continue
+			}
+			spanInfo := spanInfoByID[dispatcherID]
+			span := req.Config.Span
+			schemaID := req.Config.SchemaID
+			if spanInfo != nil {
+				if span == nil {
+					span = spanInfo.Span
+				}
+				if schemaID == 0 {
```
Comment (hongyunyan) [inline maintainer/maintainer_controller_bootstrap.go]: when will the schemaID == 0, and why we need to make schemaID = spanInfo.SchemaID here?

File: downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go [hunk 21]
```diff
@@ -368,34 +367,15 @@ func createBootstrapResponse(
...
-				ComponentStatus: d.GetComponentStatus(),
-				CheckpointTs:    d.GetCheckpointTs(),
-				BlockState:      d.GetBlockEventStatus(),
-				Mode:            d.GetMode(),
-			})
-		})
+		retrieveRedoDispatcherSpanForBootstrapResponse(manager, response)
 	}
+	retrieveDispatcherSpanForBootstrapResponse(manager, response)
+	retrieveOperatorsForBootstrapResponse(changefeedID, manager, response)
```
Comment (hongyunyan) [inline downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go]: retrieveOperatorsForBootstrapResponse is for both "redo" and "deafult" mode right?
So may be you can write like
if manager.RedoEnable{
   retrieveRedoDispatcherSpanForBootstrapResponse
} else {
  retrieveDispatcherSpanForBootstrapResponse
}

retrieveOperatorsForBootstrapResponse

File: maintainer/operator/operator_add.go [hunk 22]
```diff
@@ -44,6 +44,8 @@ type AddDispatcherOperator struct {
 	//   - The task is removed (for example, due to DDL).
 	removed        atomic.Bool
 	spanController *span.Controller
+	// This add operator may be a part of move/split operator
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply maintainer/operator/operator_add.go]: operatorType here means the logical maintainer operator type embedded into ScheduleDispatcherRequest.OperatorType (Add/Remove/Move/Split…), not the low-level ScheduleAction (Create/Remove). Dispatcher managers persist unfinished ScheduleDispatcherRequests and include them in bootstrap responses so a new maintainer can restore in-flight operators after failover. That’s why a Create/Remove request can carry OperatorType_O_Move (move is remove+add) even though the action is Create/Remove. I added detailed comments in AddDispatcherOperator to clarify this.

[the remark this answers is not in the document]
Comment (wlwilliamx) [reply maintainer/operator/operator_add.go]: Only operators that communicate via ScheduleDispatcherRequest (create/remove dispatcher) need to carry/propagate operatorType for bootstrap recovery. Some operators use dedicated request/message types (e.g. merge) and don’t go through ScheduleDispatcherRequest, so they don’t need this field; and some operators (like MoveDispatcherOperator) always send a fixed OperatorType_O_Move directly. I updated comments to make this distinction explicit.

File: maintainer/operator/operator_remove.go (hunk 18 above)
Comment (wlwilliamx) [reply maintainer/operator/operator_remove.go]: updated removeDispatcherOperator comments with the same explanation about operatorType, bootstrap recovery, and why some operators don’t need it.

File: maintainer/maintainer_controller_bootstrap.go [hunk 23]
```diff
@@ -230,9 +237,11 @@ func (c *Controller) processTableSpans(
 ) {
 	tableSpans, isTableWorking := workingTaskMap[table.TableID]
 	spanController := c.getSpanController(mode)
+	replicaSets := spanController.GetTasksByTableID(table.TableID)
+	isTableSpanExists := replicaSets != nil && len(replicaSets) > 0
 	splitEnabled := spanController.ShouldEnableSplit(table.Splitable)
 	// Add new table if not working
-	if isTableWorking {
+	if isTableWorking || isTableSpanExists {
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply maintainer/maintainer_controller_bootstrap.go]: isTableWorking comes from workingTaskMap (dispatcher-manager bootstrap snapshots), while isTableSpanExists comes from spanController state (which can be populated earlier during bootstrap by restoring in-flight operators, even if the dispatcher isn’t visible in resp.Spans yet). So isTableWorking == false && isTableSpanExists == true happens when the table exists in maintainer state but hasn’t been observed as Working on any node snapshot (e.g. Create operator still in-flight). Added comments to clarify.

File: maintainer/maintainer_controller.go [hunk 24]
```diff
@@ -174,6 +174,21 @@ func (c *Controller) HandleStatus(from node.ID, statusList []*heartbeatpb.TableS
 			continue
 		}
 		spanController.UpdateStatus(stm, status)
+
+		// If a dispatcher becomes non-working but there's no operator handling it,
+		// it means the dispatcher is removed unexpectedly (e.g. maintainer failover loses the operator),
+		// and we must reschedule it to avoid the dispatcher being lost forever.
+		if status.ComponentStatus == heartbeatpb.ComponentState_Stopped ||
```
[the remark this answers is not in the document]
Comment (wlwilliamx) [reply maintainer/maintainer_controller.go]: This fallback is reachable in practice. During maintainer failover/bootstrap, a Remove request sent by the old maintainer can be “in flight” and thus not included in the dispatcher manager’s bootstrap operators. The new maintainer may bootstrap seeing the dispatcher as Working with no in-flight operator, and then after bootstrap the in-flight Remove arrives and removes the dispatcher. Without this fallback, the span could be lost (no operator to reschedule). Therefore when we observe Stopped/Removed with op == nil (and stm.GetNodeID() == from), we mark the span absent to trigger rescheduling. This is safe under retries/out-of-order because of the nodeID check and MarkSpanAbsent’s idempotence.

File: maintainer/maintainer_controller_bootstrap.go (hunk 20 above)
Comment (hongyunyan) [reply maintainer/maintainer_controller_bootstrap.go]: schemaID in ddlSpan is 0. Will this cause a problem with the logic here?
