### PR TITLE
eventservice: fix a panic

### LINKED ISSUE #2399: CDC panic in a integration test
ref: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Fticdc%2Fpull_cdc_mysql_integration_light/detail/pull_cdc_mysql_integration_light/3891/pipeline

PR:https://github.com/pingcap/ticdc/pull/2389

```
[2025/09/29 04:26:56.963 +08:00] [INFO] [server.go:201] ["validate pd address"] [pd="[http://127.0.0.1:2379]"] [pdCount=1]
[2025/09/29 04:26:56.963 +08:00] [INFO] [server.go:236] ["parse config file path from os.Args"] [config=]
[2025/09/29 04:26:56.964 +08:00] [INFO] [server.go:320] ["Running TiCDC server in new architecture"]
panic: should not happen: sendHandshakeIfNeed should not be called concurrently [recovered]
	panic: handleLoop panic

goroutine 1604 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc05d5de270, {0x48?, 0xc05d5eea80?, 0x9be?})
	/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x9c
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc05d5de270, {0xc05d5dc700, 0x2, 0x2})
	/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x3a3
go.uber.org/zap.(*Logger).Panic(0xc003a92680, {0xc8953f7, 0x10}, {0xc05d5dc700, 0x2, 0x2})
	/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x68
github.com/pingcap/log.Panic({0xc8953f7, 0x10}, {0xc05d5dc700, 0x2, 0x2})
	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20250917021125-19901e015dc9/global.go:54 +0x72
github.com/pingcap/ticdc/utils/dynstream.(*stream[...]).handleLoop.func2()
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/stream.go:217 +0x296
panic({0xb9ca480?, 0xc059b6cf30?})
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.linux-amd64/src/runtime/panic.go:792 +0x132
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc05d5de1a0, {0x4c?, 0xc05d5ec000?, 0x703?})
	/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x9c
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc05d5de1a0, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x3a3
go.uber.org/zap.(*Logger).Panic(0xc003a92680, {0xca3d73c, 0x48}, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x68
github.com/pingcap/log.Panic({0xca3d73c, 0x48}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20250917021125-19901e015dc9/global.go:54 +0x72
github.com/pingcap/ticdc/pkg/eventservice.(*eventBroker).sendHandshakeIfNeed(0xc051cb4000, 0xc05363b540)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/pkg/eventservice/event_broker.go:457 +0xd68
github.com/pingcap/ticdc/pkg/eventservice.(*eventBroker).scanReady(0xc051cb4000, 0xc05363b540)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/pkg/eventservice/event_broker.go:419 +0x10d
github.com/pingcap/ticdc/pkg/eventservice.(*eventBroker).onNotify(0xc051cb4000, 0xc05363b540, 0x666480a39d80019, 0x66648096eb4002f)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/pkg/eventservice/event_broker.go:839 +0x285
github.com/pingcap/ticdc/pkg/eventservice.(*eventBroker).addDispatcher.func1(0x666480a39d80019, 0x66648096eb4002f)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/pkg/eventservice/event_broker.go:911 +0xd5
github.com/pingcap/ticdc/logservice/eventstore.(*eventStore).RegisterDispatcher.func3(0x666480a39d80019, 0x66648096eb4002f)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/logservice/eventstore/event_store.go:468 +0x82
github.com/pingcap/ticdc/logservice/eventstore.(*eventStore).RegisterDispatcher.func5(0x666480a39d80019)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/logservice/eventstore/event_store.go:616 +0x405
github.com/pingcap/ticdc/logservice/logpuller.(*regionEventHandler).Handle.func1(...)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/logservice/logpuller/region_event_handler.go:107
github.com/pingcap/ticdc/logservice/logpuller.(*regionEventHandler).Handle(0xc00019d280, 0xc0538c5440, {0xc03eb1c000, 0x1, 0x400})
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/logservice/logpuller/region_event_handler.go:124 +0xc6c
github.com/pingcap/ticdc/utils/dynstream.(*stream[...]).handleLoop(0xdb2f400)
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/stream.go:284 +0x932
created by github.com/pingcap/ticdc/utils/dynstream.(*stream[...]).start in goroutine 635
	/home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/stream.go:130 +0x2a5

```

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #2399 

### What is changed and how it works?

Use Double-Checked Locking Pattern to prevent the `sendHandshakeIfNeed` method from being called concurrentlly. 

#### Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lidezhu — APPROVED** [review]

File: pkg/eventservice/event_broker.go [hunk 1]
```diff
@@ -469,6 +472,8 @@ func (c *eventBroker) sendHandshakeIfNeed(task scanTask) {
 	wrapEvent := newWrapHandshakeEvent(remoteID, event)
 	c.getMessageCh(task.messageWorkerIndex, common.IsRedoMode(task.info.GetMode())) <- wrapEvent
 	updateMetricEventServiceSendCommandCount(task.info.GetMode())
+
```
Comment (lidezhu) [inline pkg/eventservice/event_broker.go:475]:
```suggestion
// Send handshake event to channel before calling `setHandshaked`
// This ensures the handshake event precedes any subsequent data events.
```
