### PR TITLE
coordinator: retry SetChangefeedProgress on etcd CAS conflict

### LINKED ISSUE #4049: Changefeed remove/pause can fail due to etcd CAS conflict when persisting progress
### What did you do?

In a TiCDC cluster with many changefeeds and frequent checkpoint persistence, we remove (or pause) a changefeed via:

- OpenAPI v2: `DELETE /api/v2/changefeeds/{changefeed_id}`
- or CLI: `cdc cli changefeed remove`

This can happen during automated test teardown or operational cleanup.

### What did you expect to see?

The request should succeed reliably, and the changefeed should enter removing/removed state.

### What did you see instead?

Occasionally the request fails with an error like:

- HTTP 500
- `[CDC:ErrMetaOpFailed] unexpected meta operation failure: update changefeed to <keyspace>/<changefeed>-2`

Root cause: `EtcdBackend.SetChangefeedProgress` performs an etcd ModRevision CAS. If the same job status key is concurrently updated (for example, by periodic checkpointTs persistence), the CAS can fail (`TxnResponse.Succeeded=false`) and the API returns `ErrMetaOpFailed`.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
N/A
```

Upstream TiKV version (execute `tikv-server --version`):

```console
N/A
```

TiCDC version (execute `cdc version`):

```console
Observed on v8.5.5 (likely affects any version with the same CAS logic).
```

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #4049

### What is changed and how it works?

Retry `EtcdBackend.SetChangefeedProgress` when etcd ModRevision CAS fails due to concurrent writers updating the same key, so admin APIs (remove/pause) won’t flake with `ErrMetaOpFailed`. Also adds a unit test covering a CAS-conflict-then-success retry.

#### Tests 

- Unit test
- Manual test

##### Will it cause performance regression or break compatibility?

No. The retry loop is bounded and only triggers on CAS conflicts; the common path is unchanged.

##### Do you need to update user documentation, design documentation or monitoring documentation?

N/A

### Release note 

```release-note
Fix flaky changefeed remove/pause failures caused by etcd CAS conflicts when persisting changefeed progress.
```

### CODE REVIEW

File: coordinator/changefeed/etcd_backend.go [hunk 1]
```diff
@@ -290,29 +291,53 @@ func (b *EtcdBackend) ResumeChangefeed(ctx context.Context,
...
-	}
+	// SetChangefeedProgress uses etcd ModRevision compare-and-swap (CAS) to avoid
+	// overwriting a newer checkpointTs written by the checkpoint updater.
+	//
+	// The checkpoint updater writes the same key periodically. If it updates the key
+	// between our Get and Txn, the compare fails and we must retry; otherwise
+	// user-facing APIs like "changefeed remove/pause" can flake with ErrMetaOpFailed.
+	const (
+		setProgressMaxRetries = 10
+		setProgressRetryDelay = 25 * time.Millisecond
```
Comment (tenfyzhong) [inline coordinator/changefeed/etcd_backend.go]: The retry delay `setProgressRetryDelay` is defined but never actually used in the retry loop. You should add a `time.Sleep(setProgressRetryDelay)` at the end of the loop body (before the next iteration) to avoid aggressive retries that could unnecessarily load etcd.

Suggestion:
```go
for attempt := 0; attempt < setProgressMaxRetries; attempt++ {
    // ... existing logic ...
    if attempt < setProgressMaxRetries-1 {
        time.Sleep(setProgressRetryDelay)
    }
}
```

**Review by tenfyzhong — APPROVED** [review]
