### PR TITLE
codec(ticdc): improve error logging for Debezium encoding failures

### LINKED ISSUE #3964: Improve error logging for Debezium encoding failures
### What happened
When Debezium encoding fails, the current error log lacks context information:
```
[ERROR] ["write Debezium field value meet error"] [error="..."]
```

This makes it difficult to debug which table/column caused the issue.

### What you expected to happen
Error log should include detailed context information:
- schema/table name
- column name
- value that caused the error
- commitTs (useful for skipping problematic events)

### Related
- tiflow issue: https://github.com/pingcap/tiflow/issues/12485
- tiflow PR: https://github.com/pingcap/tiflow/pull/12484

### PR DESCRIPTION
**Pull request by takaidohigasi**
### What problem does this PR solve?

Issue Number: close #3964 

When Debezium encoding fails, the current error log lacks context information, making it difficult to debug which table/column caused the issue.

Related tiflow PR: https://github.com/pingcap/tiflow/pull/12484

### What is changed and how it works?

Improve error logging for Debezium encoding failures by adding detailed context information.

When Debezium encoding fails, the error log now includes:
- `schema`: database/schema name
- `table`: table name
- `column`: column name that caused the error
- `value`: the actual value (truncated to 1024 bytes if too large)
- `commitTs`: the commit timestamp of the event

The `commitTs` in the log can be used to skip problematic events using checkpoint override.

**Before:**
```
[ERROR] ["write Debezium field value meet error"] [error="..."]
```

**After:**
```
[ERROR] ["failed to write Debezium field value"]
  [schema=testdb] [table=users] [column=status]
  [value=...] [commitTs=12345] [error="..."]
```

#### Tests

- Unit test

##### Will it cause performance regression or break compatibility?

No. This only affects error logging path which is not performance critical.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note

```release-note
Add CDC error log contents when debezium sink was errored
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Enhanced error logging for data field encoding operations with improved diagnostics, now capturing schema, table, and column context along with better readability of logged values.

### CODE REVIEW

File: pkg/sink/codec/debezium/codec.go [hunk 1]
```diff
@@ -56,7 +58,35 @@ func (c *dbzCodec) writeDebeziumFieldValues(
 			}
 			err = c.writeDebeziumFieldValue(writer, row, i, colInfo)
 			if err != nil {
-				log.Error("write Debezium field value meet error", zap.Error(err))
+				// Get value for logging with panic recovery and truncation
+				ft := &colInfo.FieldType
+				datum := row.GetDatum(i, ft)
+				valueStr := func() (s string) {
+					defer func() {
+						if r := recover(); r != nil {
```
Comment (wk989898) [inline pkg/sink/codec/debezium/codec.go]: I think the `recover` is not necessary
