### PR TITLE
test: fix unstable test `availability`

### LINKED ISSUE #1844: availability test is not stable
### What did you do?

test link: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Fticdc%2Fpull_cdc_mysql_integration_heavy/detail/pull_cdc_mysql_integration_heavy/2849/pipeline

### What did you expect to see?

_No response_

### What did you see instead?

Nan

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #1844 

#### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

File: tests/integration_tests/availability/capture.sh [hunk 1]
```diff
@@ -152,8 +154,11 @@ function test_expire_capture() {
 	# resume the owner
 	kill -SIGCONT $owner_pid
 
-	run_sql "UPDATE test.availability1 set val = 22 where id = 2;"
+	# delete id=3 before update id=2 to ensure downstream sync, 
+	# since we only verify id=2 in this case.
```
Comment (lidezhu) [inline tests/integration_tests/availability/capture.sh:158]:
```suggestion
	# since we only retry to check the row with id=2 in this test case.
```
