### PR TITLE
next-gen: Fix unittest

### LINKED ISSUE #2739: next-gen: Fix unittest
# Failed Case
- [x] pkg/sink/mysql
- [x] downstreamadapter/dispatcher
- [x] pkg/sink/codec/common
- [x] pkg/sink/codec/canal
- [x] pkg/sink/codec/simple
- [x] maintainer
- [x] api/middleware

### PR DESCRIPTION
**Pull request by tenfyzhong**
### What problem does this PR solve?

Issue Number: close #2739

### What is changed and how it works?

* **Makefile:** Added `unit_test_pkg` and `unit_test_pkg_next_gen` targets for running unit tests with specific package filtering and next-gen tags.
* **API Middleware:**
  * `api/middleware/middleware_classic_test.go`: Refactored tests to use `require` instead of `assert` and removed direct dependency on `appcontext.PDAPIClient`.
  * `api/middleware/middleware_nextgen_test.go`: Significantly refactored the `TestKeyspaceCheckerMiddleware` to use `gomock` for mocking `KeyspaceManager`, improved test case coverage, and added checks for response body content.
* **Dispatcher Logic:**
  * `downstreamadapter/dispatcher/basic_dispatcher.go`: Modified the `dealWithBlockEvent` function to use `!d.tableSpan.Equal(common.KeyspaceDDLSpan(d.tableSpan.KeyspaceID))` for comparing table spans, ensuring correct handling of keyspace IDs.
  * `downstreamadapter/dispatcher/event_dispatcher_test.go`: Introduced `getTestingKeyspaceID` to dynamically get the correct keyspace ID based on the kernel type. Updated test cases to use this function and ensure correct keyspace ID handling.
  * `downstreamadapter/dispatcher/redo_dispatcher_test.go`: Similar to `event_dispatcher_test.go`, updated to use `getTestingKeyspaceID` for correct keyspace ID handling in tests.
* **Maintainer Manager:**
  * `maintainer/maintainer_manager_test.go`: Updated tests to use `gomock` for mocking `KeyspaceManager` and to correctly set up the `KeyspaceMeta` based on whether the next-gen kernel is enabled.
* **Mock Keyspace Manager:**
  * `pkg/keyspace/keyspace_manager_mock.go`: Generated mock for `KeyspaceManager` interface using `mockgen`.
* **Codec and Sink Updates:**
  * `pkg/sink/codec/canal/canal_json_test.go`: Updated `TestRowKey` to handle different expected `Rowkey` formats for classic and next-gen keyspace systems.
  * `pkg/sink/codec/common/ddl_test.go`: Added initialization logic to set `TiDBServiceScope` for next-gen kernel.
  * `pkg/sink/codec/simple/encoder_test.go`: Added initialization logic to set `TiDBServiceScope` for next-gen kernel.
  * `pkg/sink/mysql/mysql_writer_test.go`: Added initialization logic to set `TiDBServiceScope` for next-gen kernel.
* **Scripts:**
  * `scripts/generate-mock.sh`: Added a line to generate the mock for `pkg/keyspace/keyspace_manager.go`.

#### Tests

* Unit test

##### Will it cause performance regression or break compatibility?

No, this PR aims to fix unittests.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note

```release-note
None
```

### CODE REVIEW

File: downstreamadapter/dispatcher/basic_dispatcher.go [hunk 1]
```diff
@@ -737,7 +737,7 @@ func (d *BasicDispatcher) dealWithBlockEvent(event commonEvent.BlockEvent) {
 	// So there won't be a related db-level ddl event is in dealing when we get update schema id events.
 	// Thus, whether to update schema id before or after current ddl event is not important.
 	// To make it easier, we choose to directly update schema id here.
-	if event.GetUpdatedSchemas() != nil && d.tableSpan != common.KeyspaceDDLSpan(d.tableSpan.KeyspaceID) {
+	if event.GetUpdatedSchemas() != nil && !d.tableSpan.Equal(common.KeyspaceDDLSpan(d.tableSpan.KeyspaceID)) {
```
Comment (wk989898) [inline downstreamadapter/dispatcher/basic_dispatcher.go]:
```suggestion
	if event.GetUpdatedSchemas() != nil && !d.IsTableTriggerEventDispatcher() {
```

**Review by wk989898 — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]
