### PR TITLE
schemastore: fix rename tables when tidb version <= v8.1.x

### LINKED ISSUE #4392: ticdc cannot sync rename tables when upstream tidb version <= v8.1
### What did you do?

1. create a tidb cluster with version v8.1.2;
2. patch cdc new arch with version v8.5.6-release.1;
3. create changefeed;
4. run the following sql in the upstream;

```
CREATE DATABASE `db_src_x`;
  CREATE DATABASE `db_dst_y`;

  CREATE TABLE `db_src_x`.`tbl_a` (
    `col_id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `col_name` VARCHAR(64) NOT NULL,
    `col_contact` VARCHAR(128) NOT NULL,
    `col_state` TINYINT NOT NULL DEFAULT 1,
    `col_ctime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `col_mtime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY `uk_col_contact` (`col_contact`),
    KEY `idx_col_name` (`col_name`)
  );

  CREATE TABLE `db_src_x`.`tbl_b` (
    `col_id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `col_code` VARCHAR(64) NOT NULL,
    `col_ref_id` BIGINT NOT NULL,
    `col_value` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `col_flag` VARCHAR(32) NOT NULL DEFAULT 'created',
    `col_ctime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `col_mtime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY `uk_col_code` (`col_code`),
    KEY `idx_col_ref_id` (`col_ref_id`),
    KEY `idx_col_ctime` (`col_ctime`)
  );

  RENAME TABLE
    `db_src_x`.`tbl_b` TO `db_dst_y`.`tbl_b`,
    `db_src_x`.`tbl_a` TO `db_dst_y`.`tbl_a`;
```

### What did you expect to see?

The rename table ddl can be sync downstream.

### What did you see instead?

The rename table ddl fail to sync downstream.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #4392 

### What is changed and how it works?

This pull request significantly improves the robustness and correctness of DDL event handling within the schema store, particularly for `RENAME TABLES` operations. It addresses a critical issue where older TiDB versions might provide incomplete old table information, by introducing a fallback mechanism that parses this data directly from the DDL query. Furthermore, it fortifies the system against potential SQL injection by ensuring all generated DDL queries properly quote schema and table identifiers. These changes enhance the reliability of schema synchronization and DDL application.

### Highlights

* **Robust RENAME TABLES Handling**: Implemented a fallback mechanism for `RENAME TABLES` DDL events to derive missing old table names from the original SQL query, specifically addressing issues in TiDB versions <= v8.1.x where this information might be incomplete.
* **Enhanced Identifier Quoting**: Refactored DDL query generation across various DDL types (`DROP VIEW`, `DROP TABLE`, `RENAME TABLE`, `EXCHANGE PARTITION`) to consistently use `common.QuoteSchema` and `common.QuoteName` for proper identifier escaping, mitigating potential SQL injection vulnerabilities.
* **Case-Insensitive Name Lookups**: Updated schema and table name lookup functions (`findSchemaIDByName`, `findTableIDByName`) to perform case-insensitive comparisons, improving flexibility and correctness.
* **Improved Error Handling for Multi-Table Renames**: Changed a warning to a panic for length mismatches in `RENAME TABLES` operations, ensuring that multi-table DDLs are applied atomically and preventing partial schema updates.
* **Comprehensive Testing**: Added extensive unit tests covering the new fallback logic for `RENAME TABLES`, cyclic rename scenarios, identifier escaping, and case-insensitive name matching.

#### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved persisted RENAME TABLE handling: safely derive missing old identifiers from SQL and stored metadata as fallbacks, prefer store metadata on conflicts (e.g., cycles), truncate mismatched inputs to a safe length, emit warnings when fallbacks/mismatches occur, and ensure emitted RENAME statements use the resolved identifiers.

* **Tests**
  * Added tests covering fallback recovery from parsed queries, metadata-driven reconciliation, and cyclic/temporary-table rename scenarios.

### CODE REVIEW

File: logservice/schemastore/persist_storage_ddl_handlers.go [hunk 1]
```diff
@@ -809,25 +851,77 @@ func buildPersistedDDLEventForRenameTables(args buildPersistedDDLEventFuncArgs)
...
+	// See https://github.com/pingcap/tidb/pull/64421 for the upstream fix.
+	queryInfos := parseRenameTablesQueryInfos(args.job.Query)
+	useQueryInfos := len(queryInfos) > 0
+	if useQueryInfos && len(queryInfos) != len(renameTableInfos) {
+		log.Panic("rename tables query info length is inconsistent with args",
+			zap.Int("queryInfosLen", len(queryInfos)),
+			zap.Int("renameArgsLen", len(renameTableInfos)),
+			zap.String("query", args.job.Query))
+	}
+	if len(renameTableInfos) > 0 && renameTableInfos[0].OldTableName.O == "" {
```
Comment (wlwilliamx) [inline logservice/schemastore/persist_storage_ddl_handlers.go]: `&& renameTableInfos[0].OldTableName.O == ""`

why do we need this?
