### PR TITLE
logpuller: fix potential stuck

### LINKED ISSUE #4359: logpuller: subscriptionClient cond pause/resume may miss wakeups
### What did you do?

log puller uses a sync.Cond to block pushRegionEventToDS while the dynamic stream area is paused. The pause/resume state (paused atomic.Bool) was updated and cond.Broadcast() was called without holding the cond’s mutex, which can lead to missed wakeups (a waiter can go to sleep after the broadcast) and result in a goroutine blocking indefinitely.

Additionally, Close() only canceled the context and closed the stream; if the client was paused, goroutines waiting on cond.Wait() had no guarantee to be woken up, risking shutdown hangs/leaks.

### What did you expect to see?

_No response_

### What did you see instead?

As described above.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #4359 

### What is changed and how it works?

This pull request addresses a potential deadlock or stuck state within the logpuller's subscription client. It enhances the robustness of the `pushRegionEventToDS` mechanism by integrating context cancellation checks and ensuring proper unblocking during client shutdown, thereby preventing indefinite waits and improving the client's lifecycle management.

### Highlights

* **Prevented potential stuck state in `pushRegionEventToDS`**: The `pushRegionEventToDS` method now checks for context cancellation (`s.ctx.Err()`) before and during its waiting loop, ensuring it can exit gracefully if the context is canceled while the client is paused.
* **Ensured thread safety for `paused` state updates**: Mutex locks (`s.mu.Lock()` and `s.mu.Unlock()`) were added around `s.paused.Store()` operations within `handleDSFeedBack` to prevent race conditions when modifying the client's paused state.
* **Guaranteed unblocking on client closure**: The `Close` method now explicitly sets `s.paused.Store(false)` and broadcasts to the condition variable (`s.cond.Broadcast()`), which ensures any goroutines blocked in `pushRegionEventToDS` are released during shutdown.
* **Added new test case for unblocking on close**: A new unit test, `TestPushRegionEventToDSUnblocksOnClose`, was introduced to verify that the `pushRegionEventToDS` method correctly unblocks when the `subscriptionClient` is closed.

#### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Subscriptions now stop promptly when cancelled and unblocks operations on close to avoid hangs.
  * Improved thread-safety around pause/resume transitions to prevent race conditions during subscription handling.

* **Tests**
  * Added tests to verify pause/unpause behavior and that blocked operations are unblocked on close.

### CODE REVIEW

File: logservice/logpuller/subscription_client.go [hunk 1]
```diff
@@ -403,17 +403,23 @@ func (s *subscriptionClient) wakeSubscription(subID SubscriptionID) {
...
+	}
 	// fast path
 	if !s.paused.Load() {
 		s.ds.Push(subID, event)
 		return
 	}
 	// slow path: wait until paused is false
 	s.mu.Lock()
-	for s.paused.Load() {
+	for s.paused.Load() && s.ctx.Err() == nil {
```
Comment (wk989898) [inline logservice/logpuller/subscription_client.go]: Why not use `for select` to capture the context error?
