### PR TITLE
ddl: fix a bug about cross-database rename table

### LINKED ISSUE #2189: rename table ddl got incorrect block tables in kafka consumer
### What did you do?

test case `cdc_kafka_simple_misc_workloads_dispatcher_index`

### What did you expect to see?

_No response_

### What did you see instead?

Table xxx doesn't exist

log
```
[persist_storage_ddl_handlers.go:617] ["buildPersistedDDLEvent for rename table"] [query="RENAME TABLE `index_Data8_v2` TO `index_Data8`"] [schemaID=257] [SchemaName=uds2] [tableName=index_Data8] [ExtraSchemaID=257] [ExtraSchemaName=uds2] [ExtraTableName=index_Data8_v2] [involvingSchemaInfo="[{\"database\":\"uds2\",\"table\":\"index_data8_v2\"},{\"database\":\"uds2\",\"table\":\"index_data8\"}]"]
...
[event_broker.go:244] ["send ddl event to dispatcher"] [dispatcherID=650566868522115211613817681609837697415] [tableID=419] [query="RENAME TABLE `uds2`.`index_data8_v2` TO `uds2`.`index_Data8`"] [commitTs=460884768068468771] [seq=3] [mode=0]
```
### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #2189

### What is changed and how it works?
Avoid rewriting the DDL query if the rename table is not cross-database
#### Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

File: logservice/schemastore/persist_storage_ddl_handlers.go [hunk 1]
```diff
@@ -634,10 +635,23 @@ func buildPersistedDDLEventForRenameTable(args buildPersistedDDLEventFuncArgs) P
...
 		// we can use event.ExtraSchemaID(even it is wrong) to update the internal state of the cdc.
 		// But event.Query will be emit to downstream(out of cdc), we must make it correct.
+		//
+		// InvolvingSchemaInfo returns the schema info involved in the job.
+		// The value should be stored in lower case.
+		oldSchemaName := args.job.InvolvingSchemaInfo[0].Database
+		oldTableName := args.job.InvolvingSchemaInfo[0].Table
+		stmt, err := parser.New().ParseOneStmt(args.job.Query, "", "")
+		if err != nil {
+			log.Error("parse statement failed for build persisted DDL event", zap.Any("DDL", args.job.Query), zap.Error(err))
```
Comment (lidezhu) [inline logservice/schemastore/persist_storage_ddl_handlers.go:645]: Don't print error log when parse fail, just print warning, and continue to construct the query.

**Review by lidezhu — APPROVED** [review]

**Review by flowbehappy — APPROVED** [review]
